version: '3.8'

networks:
  default:

services:

  mysql-db:
    container_name:  mysql-db
    image: mysql:8.0
    #command: --default-authentication-plugin=caching_sha2_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./mysqldb:/docker-entrypoint-initdb.d/
    networks:
      - default

  netapi-app:
    container_name: netapi-app
    depends_on:
      - mysql-db
    build:
      context: ./LatijnBackend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    image: guildramon/latijn-docker-image:latest
    ports:
      - $NETAPI_APP_LOCAL_PORT:$NETAPI_APP_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - default
    
  nextjs-app:
    container_name: nextjs-app
    depends_on: 
      - netapi-app
    build:
      context: ./latijnfrontend
      dockerfile: Dockerfile
    image: guildramon/latijn-docker-image:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NEXTJS_APP_LOCAL_PORT:$NEXTJS_APP_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./latijnfrontend:/app
    #  - /app/node_modules
    #  - /app/.next
    networks:
      - default

volumes: 
  mysql-volume: