// <auto-generated />
using LatijnBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LatijnBackend.Migrations
{
    [DbContext(typeof(LatijnContext))]
    partial class LatijnContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LatijnBackend.Models.Werkwoord", b =>
                {
                    b.Property<int>("WoordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WoordID"));

                    b.Property<string>("Betekenis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Conjugatie")
                        .HasColumnType("int");

                    b.Property<string>("Infinitivus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Perfectum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Praesens")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Supinum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("WoordID");

                    b.ToTable("Werkwoorden");
                });
#pragma warning restore 612, 618
        }
    }
}
