name: Push Docker image to Docker Hub

on:
  pull_request:
    branches: ["main"]

jobs:
  BuildAndPush:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:LatijnBackend/LatijnBackend"
          file: ../Dockerfile
          push: true
          tags: guildramon/latijn-docker-image:latest
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:latijnfrontend"
          push: true
          tags: guildramon/latijn-docker-image:latest
