name: Run Unit Tests on backend

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main"]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./LatijnBackend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build application
        run: dotnet build --no-restore
      - name: Run unit tests
        run: dotnet test "LatijnTest" --no-build --verbosity normal
